site_name: MemNNetSim

repo_url: https://github.com/marcus-k/MemNNetSim
repo_name: marcus-k/MemNNetSim

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - content.code.copy
    
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: table # or "table"
            docstring_style: "numpy"
            filters: ["!^_"]
            heading_level: 1
            merge_init_into_class: true
            separate_signature: true
            show_root_heading: true
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            summary: true
  - api-autonav:
      modules: ["mnns"]
      nav_section_title: Reference

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Reference
