site_name: MemNNetSim

repo_url: https://github.com/marcus-k/MemNNetSim
repo_name: marcus-k/MemNNetSim

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - navigation.tabs
    - navigation.tabs.sticky
    
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - api-autonav:
      modules: ["mnns"]
      nav_section_title: Reference

markdown_extensions:
  - toc:
      permalink: true

nav:
  - Home: index.md